[package]
name = "typyr"
version = "0.1.0"
edition = "2024"
default-run = "typyr"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
itertools = "0.14.0"
portable-pty = "0.9.0"

[[bin]]
name = "test"
path = "./src/main_1.rs"
